spring:
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: jdbc:mariadb://localhost:3306/volanaka
  application:
    name: cryptog
keycloak:
  configuration:
    realm: volanaka
    auth-server-url: http://localhost:8080
    client-id: volanaka
    client-secret: ${KEYCLOAK_CLIENT_SECRET}
    grant-type: client_credentials
    username: admin
    password: admin
    scope: openid
    admin-client-role: admin
    user-client-role: user
    jwk-set-uri: ${keycloak.configuration.auth-server-url}/protocol/openid-connect/certs
server:
  port: 8081
anchor:
  cryptog:
    api:
      url: http://localhost:3000
fineract:
  mifos:
    api:
      url: https://fineract.cb.eqima.org
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /api-docs-ui.html